// <auto-generated />
namespace Labs.Expenses.W.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class TuningTheModel : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(TuningTheModel));
        
        string IMigrationMetadata.Id
        {
            get { return "201404271333181_TuningTheModel"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
